import hashlib
import hmac
import os
import re
import secrets
import unicodedata
from contextvars import ContextVar
from datetime import datetime, timedelta, timezone
from pathlib import Path

import psycopg
from psycopg import sql
from psycopg.rows import dict_row
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
UPLOAD_ROOT = DATA_DIR / "uploads"
LEGACY_COMPANY_DB_DIR = DATA_DIR / "companies"

DATA_DIR.mkdir(exist_ok=True)
UPLOAD_ROOT.mkdir(exist_ok=True)
LEGACY_COMPANY_DB_DIR.mkdir(exist_ok=True)

load_dotenv(BASE_DIR / ".env")
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

_active_company_id = ContextVar("active_company_id", default=None)
_platform_initialized = False
_initialized_companies = set()

IDENTITY_TABLES = {
    "companies",
    "users",
    "supplier_products",
    "documents",
    "document_lines",
    "price_lists",
    "price_list_lines",
    "purchases",
}


def normalize_basic(value):
    return " ".join((value or "").lower().strip().split())


def _slugify(value):
    text = unicodedata.normalize("NFKD", value or "")
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = re.sub(r"[^A-Za-z0-9]+", "-", text).strip("-").lower()
    return text or "azienda"


def _require_database_url():
    if not DATABASE_URL:
        raise RuntimeError(
            "DATABASE_URL non trovato nel file .env. "
            "Esegui prima la configurazione PostgreSQL della 1.4C."
        )


def _raw_connection():
    _require_database_url()
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def _set_search_path(raw, schema_name):
    with raw.cursor() as cur:
        if schema_name == "public":
            cur.execute("SET search_path TO public")
        else:
            cur.execute(
                sql.SQL("SET search_path TO {}, public").format(
                    sql.Identifier(schema_name)
                )
            )


def _translate_sql(query):
    """Adatta la sintassi SQLite usata dalla baseline alla sintassi PostgreSQL."""
    q = str(query)
    had_insert_ignore = bool(
        re.search(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", q, flags=re.I)
    )
    if had_insert_ignore:
        q = re.sub(
            r"\bINSERT\s+OR\s+IGNORE\s+INTO\b",
            "INSERT INTO",
            q,
            count=1,
            flags=re.I,
        )

    # La baseline usa campi timestamp come testo.
    q = re.sub(
        r"\bCURRENT_TIMESTAMP\b(?!\s*::)",
        "CURRENT_TIMESTAMP::TEXT",
        q,
        flags=re.I,
    )

    # Placeholder sqlite -> psycopg.
    q = q.replace("?", "%s")

    # SQLite INSERT OR IGNORE -> PostgreSQL ON CONFLICT DO NOTHING.
    if had_insert_ignore and "ON CONFLICT" not in q.upper():
        q = q.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"

    return q


def _insert_table_name(query):
    match = re.match(
        r"\s*INSERT\s+(?:OR\s+IGNORE\s+)?INTO\s+([A-Za-z_][A-Za-z0-9_]*)",
        str(query),
        flags=re.I,
    )
    return match.group(1).lower() if match else None


class CursorCompat:
    def __init__(self, cursor):
        self._cursor = cursor
        self.lastrowid = None

    @property
    def rowcount(self):
        return self._cursor.rowcount

    def execute(self, query, params=()):
        original = str(query)
        translated = _translate_sql(original)
        table = _insert_table_name(original)

        wants_returning_id = (
            table in IDENTITY_TABLES
            and "RETURNING" not in translated.upper()
        )
        if wants_returning_id:
            translated = translated.rstrip().rstrip(";") + " RETURNING id"

        self._cursor.execute(translated, params or ())
        self.lastrowid = None

        if wants_returning_id:
            row = self._cursor.fetchone()
            if row:
                self.lastrowid = row.get("id") if isinstance(row, dict) else row[0]

        return self

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def close(self):
        self._cursor.close()


class ConnectionCompat:
    def __init__(self, raw):
        self._raw = raw

    def cursor(self):
        return CursorCompat(self._raw.cursor())

    def execute(self, query, params=()):
        cur = self.cursor()
        return cur.execute(query, params)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        self._raw.close()


PLATFORM_DDL = """
CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    vat_number TEXT,
    sector TEXT,
    slug TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_companies_vat
ON companies(vat_number)
WHERE vat_number IS NOT NULL AND BTRIM(vat_number) <> '';

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    full_name TEXT,
    is_platform_admin INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS user_companies (
    user_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    role TEXT NOT NULL DEFAULT 'OPERATOR',
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
    PRIMARY KEY(user_id, company_id),
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(company_id) REFERENCES companies(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sessions (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
"""

COMPANY_DDL = """
CREATE TABLE IF NOT EXISTS suppliers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    vat_number TEXT,
    category TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_suppliers_vat
ON suppliers(vat_number)
WHERE vat_number IS NOT NULL AND vat_number <> '';

CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    normalized_name TEXT,
    category TEXT,
    unit TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_products_norm ON products(normalized_name);

CREATE TABLE IF NOT EXISTS supplier_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id TEXT NOT NULL,
    supplier_code TEXT,
    original_description TEXT NOT NULL,
    product_id TEXT NOT NULL,
    UNIQUE(supplier_id, supplier_code),
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    file_hash TEXT NOT NULL UNIQUE,
    document_type TEXT,
    supplier_id TEXT,
    document_number TEXT,
    document_date TEXT,
    currency TEXT,
    total_amount NUMERIC(18,4),
    source TEXT DEFAULT 'UPLOAD',
    status TEXT NOT NULL,
    imported_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
    stored_path TEXT,
    workflow_status TEXT NOT NULL DEFAULT 'DA_GESTIRE',
    handled_at TEXT,
    review_reason TEXT,
    confirmed_at TEXT,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE TABLE IF NOT EXISTS document_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    line_number INTEGER,
    supplier_code TEXT,
    original_description TEXT,
    product_id TEXT,
    match_method TEXT,
    quantity NUMERIC(18,4),
    unit TEXT,
    unit_price NUMERIC(18,4),
    line_total NUMERIC(18,4),
    vat_rate NUMERIC(12,4),
    line_type TEXT DEFAULT 'PRODUCT',
    invoice_list_price NUMERIC(18,4),
    invoice_discount_1 NUMERIC(12,4) DEFAULT 0,
    invoice_discount_2 NUMERIC(12,4) DEFAULT 0,
    invoice_net_price NUMERIC(18,4),
    expected_net_price NUMERIC(18,4),
    price_variance_unit NUMERIC(18,4),
    price_variance_total NUMERIC(18,4),
    price_check_status TEXT,
    FOREIGN KEY (document_id) REFERENCES documents(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS price_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_hash TEXT NOT NULL UNIQUE,
    imported_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
    source TEXT DEFAULT 'UPLOAD',
    status TEXT NOT NULL DEFAULT 'IMPORTATO',
    rows_count INTEGER DEFAULT 0,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE TABLE IF NOT EXISTS price_list_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_list_id BIGINT NOT NULL,
    row_number INTEGER,
    supplier_code TEXT,
    original_description TEXT NOT NULL,
    product_id TEXT,
    match_method TEXT,
    unit TEXT,
    offered_price NUMERIC(18,4),
    list_price NUMERIC(18,4),
    discount_1 NUMERIC(12,4) DEFAULT 0,
    discount_2 NUMERIC(12,4) DEFAULT 0,
    net_price NUMERIC(18,4),
    FOREIGN KEY (price_list_id) REFERENCES price_lists(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_date TEXT NOT NULL,
    supplier_id TEXT NOT NULL,
    product_id TEXT NOT NULL,
    quantity NUMERIC(18,4) NOT NULL,
    unit_price NUMERIC(18,4) NOT NULL,
    source_document_id BIGINT,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (source_document_id) REFERENCES documents(id)
);
"""

NUMERIC_COLUMNS = {
    "documents": ["total_amount"],
    "document_lines": [
        "quantity", "unit_price", "line_total", "vat_rate",
        "invoice_list_price", "invoice_discount_1", "invoice_discount_2",
        "invoice_net_price", "expected_net_price",
        "price_variance_unit", "price_variance_total",
    ],
    "price_list_lines": [
        "offered_price", "list_price", "discount_1", "discount_2", "net_price"
    ],
    "purchases": ["quantity", "unit_price"],
}


def _ensure_numeric_columns(raw, schema_name):
    with raw.cursor() as cur:
        for table, columns in NUMERIC_COLUMNS.items():
            for column in columns:
                cur.execute(
                    """
                    SELECT data_type
                    FROM information_schema.columns
                    WHERE table_schema=%s AND table_name=%s AND column_name=%s
                    """,
                    (schema_name, table, column),
                )
                row = cur.fetchone()
                if not row:
                    continue
                if row["data_type"] in {"double precision", "real"}:
                    cur.execute(
                        sql.SQL(
                            "ALTER TABLE {}.{} ALTER COLUMN {} "
                            "TYPE NUMERIC USING {}::numeric"
                        ).format(
                            sql.Identifier(schema_name),
                            sql.Identifier(table),
                            sql.Identifier(column),
                            sql.Identifier(column),
                        )
                    )


def init_platform_db():
    global _platform_initialized
    if _platform_initialized:
        return

    raw = _raw_connection()
    try:
        _set_search_path(raw, "public")
        with raw.cursor() as cur:
            cur.execute(PLATFORM_DDL)
            cur.execute(
                """
                ALTER TABLE user_companies
                ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ACTIVE'
                """
            )
        raw.commit()
        _platform_initialized = True
    finally:
        raw.close()


def get_platform_connection():
    init_platform_db()
    raw = _raw_connection()
    _set_search_path(raw, "public")
    return ConnectionCompat(raw)


PASSWORD_ITERATIONS = 210_000
SESSION_DAYS = 7


def _normalize_email(value):
    return str(value or "").strip().lower()


def hash_password(password):
    password = str(password or "")
    if len(password) < 8:
        raise ValueError("La password deve contenere almeno 8 caratteri.")
    salt = secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        salt,
        PASSWORD_ITERATIONS,
    )
    return f"pbkdf2_sha256${PASSWORD_ITERATIONS}${salt.hex()}${digest.hex()}"


def verify_password(password, encoded):
    try:
        algorithm, iterations, salt_hex, digest_hex = encoded.split("$", 3)
        if algorithm != "pbkdf2_sha256":
            return False
        digest = hashlib.pbkdf2_hmac(
            "sha256",
            str(password or "").encode("utf-8"),
            bytes.fromhex(salt_hex),
            int(iterations),
        )
        return hmac.compare_digest(digest.hex(), digest_hex)
    except Exception:
        return False


def has_users():
    conn = get_platform_connection()
    try:
        count = conn.execute("SELECT COUNT(*) AS c FROM users").fetchone()["c"]
        return bool(count)
    finally:
        conn.close()


def create_first_admin(email, password, full_name=""):
    if has_users():
        raise ValueError("L'amministratore iniziale è già stato creato.")

    email = _normalize_email(email)
    if not email or "@" not in email:
        raise ValueError("Inserisci un indirizzo email valido.")

    conn = get_platform_connection()
    try:
        cur = conn.execute(
            """
            INSERT INTO users(email,password_hash,full_name,is_platform_admin,status)
            VALUES(?,?,?,?, 'ACTIVE')
            """,
            (email, hash_password(password), str(full_name or "").strip() or None, 1),
        )
        user_id = cur.lastrowid

        company_ids = conn.execute(
            "SELECT id FROM companies WHERE status='ACTIVE'"
        ).fetchall()
        for row in company_ids:
            conn.execute(
                """
                INSERT OR IGNORE INTO user_companies(user_id,company_id,role)
                VALUES(?,?,'ADMIN')
                """,
                (user_id, row["id"]),
            )

        conn.commit()
    finally:
        conn.close()
    return get_user(user_id)


def get_user(user_id):
    conn = get_platform_connection()
    try:
        row = conn.execute(
            """
            SELECT id,email,full_name,is_platform_admin,status,created_at
            FROM users
            WHERE id=?
            """,
            (int(user_id),),
        ).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def authenticate_user(email, password):
    email = _normalize_email(email)
    conn = get_platform_connection()
    try:
        row = conn.execute(
            """
            SELECT id,email,password_hash,full_name,is_platform_admin,status,created_at
            FROM users
            WHERE email=?
            """,
            (email,),
        ).fetchone()
    finally:
        conn.close()

    if not row or row["status"] != "ACTIVE":
        return None
    if not verify_password(password, row["password_hash"]):
        return None

    return {
        "id": row["id"],
        "email": row["email"],
        "full_name": row["full_name"],
        "is_platform_admin": row["is_platform_admin"],
        "status": row["status"],
        "created_at": row["created_at"],
    }


def create_session(user_id):
    token = secrets.token_urlsafe(32)
    expires = datetime.now(timezone.utc) + timedelta(days=SESSION_DAYS)
    conn = get_platform_connection()
    try:
        conn.execute(
            """
            INSERT INTO sessions(token,user_id,expires_at)
            VALUES(?,?,?)
            """,
            (token, int(user_id), expires.isoformat()),
        )
        conn.commit()
    finally:
        conn.close()
    return token


def get_session_user(token):
    if not token:
        return None

    conn = get_platform_connection()
    try:
        row = conn.execute(
            """
            SELECT s.token,s.expires_at,
                   u.id,u.email,u.full_name,u.is_platform_admin,u.status,u.created_at
            FROM sessions s
            JOIN users u ON u.id=s.user_id
            WHERE s.token=?
            """,
            (token,),
        ).fetchone()

        if not row:
            return None

        try:
            expires = datetime.fromisoformat(str(row["expires_at"]))
            if expires.tzinfo is None:
                expires = expires.replace(tzinfo=timezone.utc)
        except Exception:
            expires = datetime.now(timezone.utc) - timedelta(seconds=1)

        if expires <= datetime.now(timezone.utc) or row["status"] != "ACTIVE":
            conn.execute("DELETE FROM sessions WHERE token=?", (token,))
            conn.commit()
            return None

        return {
            "id": row["id"],
            "email": row["email"],
            "full_name": row["full_name"],
            "is_platform_admin": row["is_platform_admin"],
            "status": row["status"],
            "created_at": row["created_at"],
        }
    finally:
        conn.close()


def delete_session(token):
    if not token:
        return
    conn = get_platform_connection()
    try:
        conn.execute("DELETE FROM sessions WHERE token=?", (token,))
        conn.commit()
    finally:
        conn.close()


def list_user_companies(user_id):
    conn = get_platform_connection()
    try:
        rows = conn.execute(
            """
            SELECT c.id,c.name,c.vat_number,c.sector,c.slug,c.status,c.created_at,
                   uc.role
            FROM user_companies uc
            JOIN companies c ON c.id=uc.company_id
            WHERE uc.user_id=?
              AND c.status='ACTIVE'
              AND COALESCE(uc.status,'ACTIVE')='ACTIVE'
            ORDER BY c.name
            """,
            (int(user_id),),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def user_has_company(user_id, company_id):
    conn = get_platform_connection()
    try:
        row = conn.execute(
            """
            SELECT role
            FROM user_companies
            WHERE user_id=? AND company_id=?
              AND COALESCE(status,'ACTIVE')='ACTIVE'
            """,
            (int(user_id), int(company_id)),
        ).fetchone()
        return row["role"] if row else None
    finally:
        conn.close()


def link_user_to_company(user_id, company_id, role="OPERATOR"):
    role = str(role or "OPERATOR").upper()
    if role not in {"ADMIN", "OPERATOR"}:
        raise ValueError("Ruolo non valido.")

    conn = get_platform_connection()
    try:
        conn.execute(
            """
            INSERT INTO user_companies(user_id,company_id,role)
            VALUES(?,?,?)
            ON CONFLICT(user_id,company_id)
            DO UPDATE SET role=excluded.role
            """,
            (int(user_id), int(company_id), role),
        )
        conn.commit()
    finally:
        conn.close()


def list_company_users(company_id):
    conn = get_platform_connection()
    try:
        rows = conn.execute(
            """
            SELECT u.id,u.email,u.full_name,
                   COALESCE(uc.status,'ACTIVE') AS status,
                   u.created_at,uc.role
            FROM user_companies uc
            JOIN users u ON u.id=uc.user_id
            WHERE uc.company_id=?
            ORDER BY u.full_name,u.email
            """,
            (int(company_id),),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def create_company_user(company_id, email, password, full_name="", role="OPERATOR"):
    email = _normalize_email(email)
    if not email or "@" not in email:
        raise ValueError("Inserisci un indirizzo email valido.")

    role = str(role or "OPERATOR").upper()
    if role not in {"ADMIN", "OPERATOR"}:
        raise ValueError("Ruolo non valido.")

    conn = get_platform_connection()
    try:
        existing = conn.execute(
            "SELECT id FROM users WHERE email=?",
            (email,),
        ).fetchone()

        if existing:
            user_id = existing["id"]
            already = conn.execute(
                """
                SELECT 1 FROM user_companies
                WHERE user_id=? AND company_id=?
                """,
                (user_id, int(company_id)),
            ).fetchone()
            if already:
                raise ValueError("Questo utente è già associato all'azienda.")
        else:
            cur = conn.execute(
                """
                INSERT INTO users(email,password_hash,full_name,is_platform_admin,status)
                VALUES(?,?,?,?, 'ACTIVE')
                """,
                (
                    email,
                    hash_password(password),
                    str(full_name or "").strip() or None,
                    0,
                ),
            )
            user_id = cur.lastrowid

        conn.execute(
            """
            INSERT INTO user_companies(user_id,company_id,role)
            VALUES(?,?,?)
            """,
            (user_id, int(company_id), role),
        )
        conn.commit()
    finally:
        conn.close()

    return {**get_user(user_id), "role": role}



def update_company_user_role(company_id, user_id, role, acting_user_id=None):
    role = str(role or "").upper()
    if role not in {"ADMIN", "OPERATOR"}:
        raise ValueError("Ruolo non valido.")

    company_id = int(company_id)
    user_id = int(user_id)
    acting_user_id = int(acting_user_id) if acting_user_id is not None else None

    conn = get_platform_connection()
    try:
        membership = conn.execute(
            """
            SELECT role,COALESCE(status,'ACTIVE') AS status
            FROM user_companies
            WHERE company_id=? AND user_id=?
            """,
            (company_id, user_id),
        ).fetchone()
        if not membership:
            raise ValueError("Utente non appartenente a questa azienda.")

        if acting_user_id == user_id and membership["role"] == "ADMIN" and role != "ADMIN":
            raise ValueError("Non puoi toglierti il ruolo di amministratore.")

        if membership["role"] == "ADMIN" and role != "ADMIN" and membership["status"] == "ACTIVE":
            admins = conn.execute(
                """
                SELECT COUNT(*) AS c
                FROM user_companies
                WHERE company_id=? AND role='ADMIN'
                  AND COALESCE(status,'ACTIVE')='ACTIVE'
                """,
                (company_id,),
            ).fetchone()["c"]
            if int(admins or 0) <= 1:
                raise ValueError("Deve rimanere almeno un amministratore attivo.")

        conn.execute(
            "UPDATE user_companies SET role=? WHERE company_id=? AND user_id=?",
            (role, company_id, user_id),
        )
        conn.commit()
    finally:
        conn.close()

    return {"id": user_id, "role": role}


def set_company_user_status(company_id, user_id, status, acting_user_id=None):
    status = str(status or "").upper()
    if status not in {"ACTIVE", "INACTIVE"}:
        raise ValueError("Stato utente non valido.")

    company_id = int(company_id)
    user_id = int(user_id)
    acting_user_id = int(acting_user_id) if acting_user_id is not None else None

    conn = get_platform_connection()
    try:
        membership = conn.execute(
            """
            SELECT role,COALESCE(status,'ACTIVE') AS status
            FROM user_companies
            WHERE company_id=? AND user_id=?
            """,
            (company_id, user_id),
        ).fetchone()
        if not membership:
            raise ValueError("Utente non appartenente a questa azienda.")

        if status == "INACTIVE" and acting_user_id == user_id:
            raise ValueError("Non puoi disattivare il tuo stesso account.")

        if status == "INACTIVE" and membership["role"] == "ADMIN" and membership["status"] == "ACTIVE":
            admins = conn.execute(
                """
                SELECT COUNT(*) AS c
                FROM user_companies
                WHERE company_id=? AND role='ADMIN'
                  AND COALESCE(status,'ACTIVE')='ACTIVE'
                """,
                (company_id,),
            ).fetchone()["c"]
            if int(admins or 0) <= 1:
                raise ValueError("Non puoi disattivare l'ultimo amministratore attivo.")

        conn.execute(
            "UPDATE user_companies SET status=? WHERE company_id=? AND user_id=?",
            (status, company_id, user_id),
        )
        conn.commit()
    finally:
        conn.close()

    return {"id": user_id, "status": status}


def reset_company_user_password(company_id, user_id):
    company_id = int(company_id)
    user_id = int(user_id)

    conn = get_platform_connection()
    try:
        membership = conn.execute(
            "SELECT 1 FROM user_companies WHERE company_id=? AND user_id=?",
            (company_id, user_id),
        ).fetchone()
        if not membership:
            raise ValueError("Utente non appartenente a questa azienda.")

        company_count = conn.execute(
            "SELECT COUNT(*) AS c FROM user_companies WHERE user_id=?",
            (user_id,),
        ).fetchone()["c"]
        if int(company_count or 0) > 1:
            raise ValueError(
                "Questo utente è associato a più aziende. Il reset password deve essere eseguito dal Gestore piattaforma."
            )

        temporary_password = secrets.token_urlsafe(9)
        conn.execute(
            "UPDATE users SET password_hash=?, status='ACTIVE' WHERE id=?",
            (hash_password(temporary_password), user_id),
        )
        conn.execute("DELETE FROM sessions WHERE user_id=?", (user_id,))
        conn.commit()
    finally:
        conn.close()

    return temporary_password


def list_companies():
    conn = get_platform_connection()
    try:
        rows = conn.execute(
            """
            SELECT id,name,vat_number,sector,slug,status,created_at
            FROM companies
            WHERE status='ACTIVE'
            ORDER BY name
            """
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def get_company(company_id):
    conn = get_platform_connection()
    try:
        row = conn.execute(
            """
            SELECT id,name,vat_number,sector,slug,status,created_at
            FROM companies
            WHERE id=? AND status='ACTIVE'
            """,
            (int(company_id),),
        ).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def create_company(name, vat_number="", sector=""):
    name = str(name or "").strip()
    vat_number = str(vat_number or "").strip().upper()
    sector = str(sector or "").strip()

    if not name:
        raise ValueError("Inserisci il nome dell'azienda.")

    conn = get_platform_connection()
    try:
        if vat_number:
            existing = conn.execute(
                "SELECT id,name FROM companies WHERE UPPER(vat_number)=UPPER(?)",
                (vat_number,),
            ).fetchone()
            if existing:
                raise ValueError(
                    f"Esiste già un'azienda con questa P.IVA: {existing['name']}."
                )

        base_slug = _slugify(name)
        slug = base_slug
        n = 2
        while conn.execute("SELECT 1 FROM companies WHERE slug=?", (slug,)).fetchone():
            slug = f"{base_slug}-{n}"
            n += 1

        cur = conn.execute(
            """
            INSERT INTO companies(name,vat_number,sector,slug)
            VALUES(?,?,?,?)
            """,
            (name, vat_number or None, sector or None, slug),
        )
        company_id = cur.lastrowid
        conn.commit()
    finally:
        conn.close()

    init_company_db(company_id)
    return get_company(company_id)


def set_active_company(company_id):
    company = get_company(company_id)
    if not company:
        raise ValueError("Azienda non valida o non attiva.")
    return _active_company_id.set(int(company_id))


def reset_active_company(token):
    _active_company_id.reset(token)


def get_active_company_id():
    company_id = _active_company_id.get()
    if company_id is None:
        raise RuntimeError("Nessuna azienda selezionata.")
    return int(company_id)


def company_schema_name(company_id):
    return f"company_{int(company_id):06d}"


def company_db_path(company_id):
    """Percorso legacy SQLite, mantenuto solo per eventuali strumenti di recupero."""
    return LEGACY_COMPANY_DB_DIR / f"company_{int(company_id):06d}.db"


def get_company_upload_dir(company_id=None):
    company_id = int(company_id or get_active_company_id())
    path = UPLOAD_ROOT / f"company_{company_id:06d}"
    path.mkdir(parents=True, exist_ok=True)
    return path


def init_company_db(company_id):
    company_id = int(company_id)
    schema_name = company_schema_name(company_id)

    if company_id in _initialized_companies:
        return

    raw = _raw_connection()
    try:
        with raw.cursor() as cur:
            cur.execute(
                sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(
                    sql.Identifier(schema_name)
                )
            )
        _set_search_path(raw, schema_name)
        with raw.cursor() as cur:
            cur.execute(COMPANY_DDL)
        _ensure_numeric_columns(raw, schema_name)
        raw.commit()
        _initialized_companies.add(company_id)
    except Exception:
        raw.rollback()
        raise
    finally:
        raw.close()


def get_connection(company_id=None):
    company_id = int(company_id or get_active_company_id())
    if not get_company(company_id):
        raise RuntimeError("Azienda non valida o non attiva.")

    init_company_db(company_id)
    raw = _raw_connection()
    _set_search_path(raw, company_schema_name(company_id))
    return ConnectionCompat(raw)


def next_text_id(conn, table, prefix):
    # table e prefix sono controllati dal codice applicativo, non dall'utente.
    rows = conn.execute(
        f"SELECT id FROM {table} WHERE id LIKE ?",
        (f"{prefix}%",),
    ).fetchall()
    nums = []
    for row in rows:
        try:
            nums.append(int(row["id"][len(prefix):]))
        except Exception:
            pass
    return f"{prefix}{(max(nums) if nums else 0) + 1:04d}"
